### ISSUE TITLE
Inspect possible glitch in ServiceLogPersister

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#203]
Inspect this:

```
Exception in thread "Thread-13" com.hazelcast.core.RuntimeInterruptedException: Thread-13 is interrupted! Operation: BLOCKING_ADD_KEY
        at com.hazelcast.impl.BaseManager.handleInterruptedException(BaseManager.java:536)
        at com.hazelcast.impl.BlockingQueueManager$MasterOp.handleInterruption(BlockingQueueManager.java:630)
        at com.hazelcast.impl.BaseManager$ResponseQueueCall.waitAndGetResult(BaseManager.java:616)
        at com.hazelcast.impl.BaseManager$ResponseQueueCall.getRedoAwareResult(BaseManager.java:628)
        at com.hazelcast.impl.BaseManager$ResponseQueueCall.getResult(BaseManager.java:623)
        at com.hazelcast.impl.BaseManager$RequestBasedCall.getResultAsBoolean(BaseManager.java:437)
        at com.hazelcast.impl.BaseManager$ResponseQueueCall.getResultAsBoolean(BaseManager.java:544)
        at com.hazelcast.impl.BlockingQueueManager.addKey(BlockingQueueManager.java:559)
        at com.hazelcast.impl.BlockingQueueManager.storeQueueItem(BlockingQueueManager.java:261)
        at com.hazelcast.impl.BlockingQueueManager.offer(BlockingQueueManager.java:203)
        at com.hazelcast.impl.BlockingQueueManager.offer(BlockingQueueManager.java:191)
        at com.hazelcast.impl.QProxyImpl$QProxyReal.put(QProxyImpl.java:248)
        at com.hazelcast.impl.QProxyImpl.put(QProxyImpl.java:171)
        at cz.cuni.mff.d3s.been.logging.ServiceLogPersister$ServiceLogPersisterThread.persist(ServiceLogPersister.java:184)
        at cz.cuni.mff.d3s.been.logging.ServiceLogPersister$ServiceLogPersisterThread.run(ServiceLogPersister.java:159)
`
```

**Comment by radek-macha** [comment]
Not a glitch, just some overzealous logging going on.

**Comment by radek-macha** [comment]
Actually is a glitch, the `BlockingQueue` implementation Hazelcast provides throws `com.hazelcast.core.RuntimeInterruptedException` instead of `java.lang.InterruptedException`.
