### ISSUE TITLE
Results Repository

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#77]
Basic analysis of RR features.

**Comment by kubamracek** [comment]
When storing a result, the results gets written into Mongo correctly, but afterwards, this exception is thrown:

```
17:28:29.898 [hz._hzInstance_1_dev.cached.thread-1] ERROR com.hazelcast.impl.ListenerManager - [195.113.16.3]:5701 [dev] Caught error while calling event listener; cause: null
java.lang.NullPointerException: null
    at cz.cuni.mff.d3s.been.resultsrepository.ResultCounterListener.balanceLoad(ResultCounterListener.java:52) ~[classes/:na]
    at cz.cuni.mff.d3s.been.resultsrepository.ResultCounterListener.itemAdded(ResultCounterListener.java:40) ~[classes/:na]
    at com.hazelcast.impl.ListenerManager.callListener(ListenerManager.java:425) ~[hazelcast-2.5.jar:2.5]
    at com.hazelcast.impl.ListenerManager.callListeners(ListenerManager.java:334) ~[hazelcast-2.5.jar:2.5]
    at com.hazelcast.impl.BaseManager$2.run(BaseManager.java:1391) [hazelcast-2.5.jar:2.5]
    at com.hazelcast.impl.executor.ParallelExecutorService$ParallelExecutorImpl$ExecutionSegment.run(ParallelExecutorService.java:212) [hazelcast-2.5.jar:2.5]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_07]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_07]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_07]
    at com.hazelcast.impl.ExecutorThreadFactory$1.run(ExecutorThreadFactory.java:38) [hazelcast-2.5.jar:2.5]
```

**Comment by radek-macha** [comment]
@sixtam This issue seems stale: the primarily intended one-way functionality has been implemented and tested for some time now. We could consider closing it.

**Comment by sixtam** [comment]
Ack.
