### ISSUE TITLE
IndexOutOfBoundsException in Monitoring thread

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#87]
Running HR for a while resulted in 

Exception in thread "Thread-10" java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at cz.cuni.mff.d3s.been.detectors.Detector.calculateDifferentialSample(Detector.java:68)
    at cz.cuni.mff.d3s.been.detectors.Detector.generateSample(Detector.java:45)
    at cz.cuni.mff.d3s.been.detectors.Monitoring$1.run(Monitoring.java:60)

**Comment by sixtam** [comment]
The error is caused by adding (removing?) network adapters, file systems, etc. For example plugging in an USB drive causes the error.
